[pytest]

testpaths = tests

python_files = test_*.py
python_classes = Test*
python_functions = test_*

addopts = -v

markers =
    smoke: Critical smoke tests
    regression: Full regression tests
    authentication: Authentication API tests
    products: Products API tests
    carts: Cart API tests
    orders: Orders API tests