# =====================================================
# This file is home for all the configuration
# related to the project. Whenever project runs
# this file is invoked first.
# =====================================================
environment: qa

api:
  verify_ssl: true

timeouts:
  connection: 10
  request: 30

authentication:
  login_endpoint: /auth/login
  username: mor_2314
  password: 83r5^_

logging:
  level: INFO

reporting:
  allure_results_directory: reports/allure-results